import type { Metadata } from 'next'
// import {Inter} from "next/font"
import Loadedcontextprovider from './mycomps/context/Loadingcontext'
import './globals.css'



export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-gray-100'>
        <Loadedcontextprovider>
        {children}

        </Loadedcontextprovider>
      </body>
    </html>
  );
}
